server:
  port: 9090

spring:
  data:
    mongodb:
      authentication-database: admin
      username: mutantuser
      password: mutantpass
      database: mutantdb
      port: 27017
      host: localhost
      repositories:
        type: auto
      auto-index-creation: true